image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  only:
    - master

test:
  stage: test
  script:
    - npm run lint

deploy:
  stage: deploy
  script:
    - npm run build-prod