cache:
  paths:
    - node_modules/

stages:
  # - build
  # - test
  # - deploy
  - publish

# build:
#   image: node:latest
#   stage: build
#   script:
#     - npm install
#     - npm run build-prod
#   artifacts:
#       paths:
#         - dist
#       expire_in: 1 hour

# test:
#   image: node:latest
#   stage: test
#   script:
#     - npm install
#     - npm run lint
#     - npm run test

# deploy:
#   image: docker:latest
#   services:
#     - docker:dind
#   stage: deploy
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#   script:
#     - docker build -t "$CI_REGISTRY_IMAGE:1.0" .
#     - docker push "$CI_REGISTRY_IMAGE:1.0"
#   after_script:
#     - docker logout $CI_REGISTRY
#   only:
#     - master

publish:
  image: gitlab/dind
  services:
    - docker:dind
  stage: publish
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)

    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PASS" | tr -d '\r' | ssh-add - > /dev/null

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ##
    ## Optionally, if you will be using any Git commands, set the user name and
    ## and email.
    ##
    #- git config --global user.email "user@example.com"
    #- git config --global user.name "User name"
  script:
    - ssh StrictHostKeyChecking=no root@188.166.124.226
    - docker stop keepadoo
    - exit
  after_script:
    - docker logout $CI_REGISTRY