cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build
  only:
    - master

test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm run lint

deploy:
  image: docker:latest
  stage: deploy
  script:
    - docker image build -t utukku/keepadoo:1.0 .