cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - publish
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build-prod
  artifacts:
    paths:
      - dist
    expire_in: 1 hour

test:
  image: node:latest
  stage: test
  script:
    - npm run lint
    - npm run test

publish:
  image: docker:latest
  services:
    - docker:dind
  stage: publish
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:1.0" .
    - docker push "$CI_REGISTRY_IMAGE:1.0"
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - master

deploy:
  image: docker:git
  services:
    - docker:dind
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$RANDOM_VARIABLE" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - cat ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no root@188.166.124.226 < ./deploy.sh
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - master
