language: node_js
node_js:
  - '10'
dist: trusty
sudo: true
services:
  - docker
cache:
  directories:
    - node_modules
before_script:
  - npm install -g @angular/cli
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
jobs:
  include:
    - stage: check
      script:
        - yarn test
        - yarn lint
    - stage: build
      script:
        - yarn build-prod
    - stage: publish
      # if: branch = master
      script:
        - yarn docker-build
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker login --username=_ --password=$HEROKU_KEY registry.heroku.com
        - yarn docker-push-heroku
        - yarn release-heroku
        - yarn docker-push
