language: node_js
node_js:
  - '10'
dist: trusty
sudo: false

services:
  - docker

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - yarn test
  - yarn lint
  - yarn docker-hub-build
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - yarn docker-push
