language: node_js
node_js:
  - '10'
dist: trusty
sudo: true
services:
  - docker
cache:
  directories:
    - node_modules
before_script:
  - npm install -g @angular/cli
jobs:
  include:
    - stage: check
      script:
        - yarn test
        - yarn lint
    - stage: build
      script:
        - yarn build-prod

before_deploy:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
 deploy:
  provider: script
  script:
        yarn docker-build;
        yarn login-heroku;
        yarn push-heroku;
        yarn release-heroku;
  on:
    all_branches: true