language: node_js
node_js:
  - '10'
dist: trusty
sudo: false

services:
  - docker

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

jobs:
  include:
    - stage: check
      script:
        - yarn test
        - yarn lint
    - stage: build
      script:
        - yarn docker-hub-build
    - stage: publish
      branches:
        only:
          - master
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - yarn docker-push
