language: node_js
node_js:
  - '10'
dist: trusty
sudo: true
services:
  - docker
cache: yarn
before_script:
  - npm install -g @angular/cli
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
jobs:
  include:
    - stage: build
      script:
        - ls
        - yarn build-prod
    - stage: check
      script:
        - ls
        - yarn test
        - yarn e2e:ci
        - yarn lint
    - stage: publish
      if: branch = master
      script:
        - yarn docker-build
        - yarn login-heroku
        - yarn push-heroku
        - yarn release-heroku
