language: node_js
node_js:
  - '10'
dist: trusty
sudo: false
services:
  - docker
cache:
  directories:
    - node_modules
before_script:
  - npm install -g @angular/cli
jobs:
  include:
    - stage: check
      script:
        - yarn test
        - yarn lint
    - stage: build
      script:
        - yarn build-prod
    - stage: publish
      if: branch = master
      script:
        - yarn docker-hub-build
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - yarn docker-push

before_deploy:
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
deploy:
  provider: script
  script:
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    - heroku container:release web --app $HEROKU_APP_NAME
