language: node_js
node_js:
  - '8'
dist: trusty
sudo: required

services:
  - docker

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - yarn test
  - yarn lint
  - yarn docker-hub-build
